apiVersion: v1
kind: Service
metadata:
  name: firefusion-frontend
  namespace: firefusion
  labels:
    app.kubernetes.io/name: firefusion-frontend
    app.kubernetes.io/part-of: firefusion-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: firefusion-frontend

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP