apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      cloud.firefusion.io/provider: azure

images:
  - name: firefusion/firefusion-api
    newName: docker.io/ashanin24x7/firefusion-api
    newTag: 152d806

  - name: firefusion/model-api
    newName: docker.io/ashanin24x7/model-api
    newTag: 152d806

  - name: firefusion/aggregator-api
    newName: docker.io/ashanin24x7/aggregator-api
    newTag: 152d806

  - name: docker.io/ashanin24x7/firefusion-frontend
    newName: docker.io/ashanin24x7/firefusion-frontend
    newTag: 1a8a888

patches:
  - path: frontend-service-loadbalancer.yaml