apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: firefusion-platform
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: alloy

  ports:
    - name: http
      protocol: TCP
      port: 12345
      targetPort: http
