apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: firefusion-platform
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: tempo

  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: http

    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc

    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
